package com.fondosGFT.fondosGFT.model.client.dto;

import com.fondosGFT.fondosGFT.model.investment.dto.InvestmentResponseDTO;
// NOTE: The package path for 'com.pruebagft.gestionFondosGFT.util.enums.NotificationType'
// seems inconsistent with your main project package 'com.fondosGFT.fondosGFT'.
// Please verify the correct package for NotificationType in your project.
import com.pruebagft.gestionFondosGFT.util.enums.NotificationType;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.util.List;

/**
 * Data Transfer Object (DTO) designed for sending client information as part of an API response.
 * This DTO encapsulates a comprehensive view of a client, including their personal details,
 * financial summary, notification preferences, and a list of their active investments.
 * It ensures that only relevant data is exposed to the client consuming the API.
 * <p>
 * Lombok annotations are used here to streamline development:
 * <ul>
 * <li>{@code @Data}: Automatically generates standard methods like getters, setters,
 * {@code equals()}, {@code hashCode()}, and {@code toString()}.</li>
 * <li>{@code @NoArgsConstructor}: Creates a constructor with no arguments, useful for
 * object instantiation without initial field values.</li>
 * <li>{@code @AllArgsConstructor}: Generates a constructor that includes all fields as arguments,
 * allowing for convenient initialization of all properties.</li>
 * </ul>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class ClientResponseDTO {
    /**
     * The unique identifier for the client. This ID is typically generated by the system
     * and used to uniquely identify the client across the application.
     */
    private String id;
    /**
     * The first name of the client.
     */
    private String firstName;
    /**
     * The last name of the client.
     */
    private String lastName;
    /**
     * The city where the client resides.
     */
    private String city;
    /**
     * The client's current aggregated balance across all their managed accounts or investments.
     */
    private BigDecimal currentBalance;
    /**
     * The client's preferred method for receiving notifications.
     * This field uses the {@link NotificationType} enum to specify options such as EMAIL, SMS, or NONE.
     * @see NotificationType
     */
    private NotificationType notificationPreference;
    /**
     * The client's primary phone number, used for communication purposes.
     */
    private String phoneNumber;
    /**
     * The client's primary email address, used for electronic communication.
     */
    private String email;
    /**
     * A list of investments currently active for this client. Each investment is represented by
     * an {@link InvestmentResponseDTO}, providing a summary of their current holdings.
     */
    private List<InvestmentResponseDTO> activeInvestments; // To display current investments
}