package com.fondosGFT.fondosGFT.model.fund.dto;


import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

/**
 * Data Transfer Object (DTO) representing an investment fund's basic information.
 * This DTO is typically used to transfer fund data between different layers of the application,
 * such as from the service layer to the controller, or as part of API responses.
 * It encapsulates key attributes of a fund, including its identifier, name,
 * product type, and the minimum subscription amount required.
 * <p>
 * Lombok annotations are utilized to reduce boilerplate code:
 * <ul>
 * <li>{@code @Data}: Automatically generates getters, setters, {@code equals()},
 * {@code hashCode()}, and {@code toString()} methods for all fields.</li>
 * <li>{@code @NoArgsConstructor}: Creates a constructor with no arguments, useful for
 * frameworks that require a default constructor (e.g., for JSON deserialization).</li>
 * <li>{@code @AllArgsConstructor}: Generates a constructor with arguments for all fields,
 * providing a convenient way to initialize all properties upon object creation.</li>
 * </ul>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class FundDTO {

    /**
     * The unique identifier for the fund.
     * This ID is typically generated by the persistence layer.
     */
    private String id;
    /**
     * The official name of the investment fund.
     */
    private String name;
    /**
     * The type of product the fund represents (e.g., "Equity Fund", "Bond Fund", "Mixed Fund").
     */
    private String productType;
    /**
     * The minimum amount required for a single subscription to this fund.
     * This field uses {@link BigDecimal} for precise monetary calculations.
     */
    private BigDecimal minimumSubscriptionAmount;
}